name: tailscale-runner
on:
  workflow_dispatch:
  push:
permissions:
  id-token: write # Required for OIDC
  contents: write # Thêm dòng này để có quyền push

jobs:
  tailscale-runner:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Set the maximum runtime for this job to 20 minutes
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # CHỈ CẦN CÁI NÀY để giữ token cho push
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - name: Runner tailscale
        env:
          RUNNER_TAILSCALE_DOTENVRTDB_URL: ${{ secrets.RUNNER_TAILSCALE_DOTENVRTDB_URL }}
        run: |
          npx --yes @tltdh61/dotenvrtdb -eUrl "$RUNNER_TAILSCALE_DOTENVRTDB_URL" -- node ./bin/runner-sync.js --verbose
      - name: ⏳ Keep Alive
        run: |
          npx --yes @ongtrieuhau861457/runner-keep-alive --interval 60 --services All
